### PR TITLE
Add GitHub actions to build for all plattforms with buildx

### PR DESCRIPTION
**Pull request by jkoan**
**By submitting this pull request, I confirm the following:**
*Please fill in any appropriate check-boxes, e.g: [X]*

-   [x]   I have read and understood the [contributors guide](https://github.com/christronyxyocum/tronitor/blob/master/.github/CONTRIBUTING.md), as well as this entire template.
-   [x]   I have made only one major change in my proposed changes.: -> I had to fix some additional things (see commits) to get it working.
-   [x]   I have commented my proposed changes within the code.
-   [x]   I have tested my proposed changes, and have included unit tests where possible. -> See Github Actions Checks
-   [x]   I am willing to help maintain this change if there are issues with it later. -> Just Tag me on any issue related to my changes ;-)
-   [x]   I give this submission freely and claim no ownership.
---
**What does this PR aim to accomplish?:**
This PR aims to introduce Github Actions in order to use buildx to build the image for multiple architectures.

**How does this PR accomplish the above?:**
Use Github Actions to checkout the repo, install qemu, install buldx and after that build the image for the different platforms

**What documentation changes (if any) are needed to support this PR?:**
I don't think much is needed here.

**Additional comments:**
First i haven't seen that the repo already uses TravisCI so i wanted to use Github Actions to build and upload with buildx for all architectures.

### CODE REVIEW

**Comment by tronyx** [comment]
What exactly is this trying to accomplish? You didn't put any information other than the title. I'm already using Travis CI to test and build.

**Comment by jkoan** [comment]
Hi @tronyx,

my goal is to build for all available platforms with docker buildx to provide arm-v7 as well as my QNAP Nas uses this Architecture and i was able to manually build for this. 
When i first started to work on this i haven't seen that you are already using TravisCI, so my idea was to use Github Actions as i know then had existing actions to install qemu and buildx automatically. I i started working on this. 
As a mistake i opened up the PR to early so i just edited the title to include WIP to indicate that its in the works.
In the meantime i continued the work and edited the description.

**Comment by tronyx** [comment]
Oh, ok, that makes sense to me know. I like the concept and appreciate the time you're putting into it.

**Comment by jkoan** [comment]
PR ready :-)

You can see the results here: https://github.com/jkoan/Docker-Nagios/runs/6554860687

Currently it has no upload included, but this can easily be added.
Just tell me if you want me to add this as well.

If you wane use GitHub Actions you probably need to enable it on this repo as well.

**Comment by tronyx** [comment]
This is awesome, thank you. Would definitely want to add in the image upload to Docker Hub. I'll look into enabling the actions for this repo too.

**Pull request merged**
